### PR TITLE
Remove node_modules from repository

### PR DESCRIPTION
**Pull request by johanjbbc**
the modules contain several files with local specific information (such as paths),
and will lead to merge conflicts.

The folder is removed from repository and added to gitignore.

### CODE REVIEW

**Comment by braima01** [comment]
Looks ok!

**Comment by bcmn** [comment]
I think this is correct -- though it might be worth adding .log as I think NPM can generate quite lengthy logs if instructed to by the user?

**Comment by ThomasCampbellBBC** [comment]
We need to make sure everything needed to run code and tests is included in package.json so that a npm install gets people setup with everything they need.

**Comment by ThomasCampbellBBC** [comment]
We might want a installDependencies script which does things like npm install -g mocha, and any other required cli nodes.

**Comment by bcmn** [comment]
I tested this ☝🏼 from a completely new clone and without a global installation of mocha, so long as you use npm test and npm install it works as expected. 

I also found two JSDOM dev-dependencies which I don't think are used any more. I'm also unsure whether AMD-loader should be in dependencies or dev-dependencies? It looks like we removed Require in favour of it, so I think dependencies is correct.

**Comment by johanjbbc** [comment]
@ThomasCampbellBBC 
I think it would be nice with this, or a confluence page/readme. I'd suggest we create a separate ticket for it.

@bcmn 
As I'm not very experienced with node I don't really know. Though, if we use it under dependencies, does that mean that the device we run it on (example and Android phone) must have amd-loader installed?

**Pull request merged**
