### PR TITLE
Feature/pickmixapp 1681 cancel download

### PR DESCRIPTION
**Pull request by johanjbbc**
Add cancel to packages

To be able to cancel in the JS side, you need to call list in packages and make sure the package id of the targeted download is valid.

See https://jira.dev.bbc.co.uk/browse/PICMIXAPP-1681

This PR will not handle update. See "Scenario 5: Cancelling an update" in the ticket.

This PR has only been tested with unit tests, and need to be integrated with native side code. 

TEsts are places in gmi-extensions/Packages

### CODE REVIEW

**Comment by johanjbbc** [comment]
Note that before https://github.com/bbc/childrens-third-party-starter-pack/pull/25 is merged, this PR will look like it edits 3000+ files. There's actually only two files modified. I suggest review to wait until PR 25 is done.

**Comment by Mikeypilk** [comment]
I agree that we should get rid of node modules.  I think we should move all the tests into folders like you have started doing.

I moved to a more standard way of creating the names for the **it** and **describe**, for tests I think it would look better if these tests matched the ones I have made.

**Comment by johanjbbc** [comment]
@Mikeypilk 
Great suggestions, can you add some comments in the code, like "text should be: xxxx" etc?
It will be much easier for me to make the changes. If there's a lot of similar things (like the it text, probably apply on all it calls) then it's enough to just mention it once.

**Comment by ThomasCampbellBBC** [comment]
Closing pull request as am going to remove large files from repo. Should be able to recreate after from branch after that is done.

**Pull request closed without merging**
